### ISSUE TITLE
Internal server error viewing newly created wireguard device

### ISSUE THREAD

**Issue by ligi** [Shard-Labs/docker-wireguard#21]
I tried to add my first wireguard device in dappnode - but got this:
![image](https://user-images.githubusercontent.com/111600/133887517-d19232fd-a52f-498f-9028-0864826e0817.png)

```
Error: Error fetching credentials: Internal Server Error {"errno":-2,"code":"ENOENT","syscall":"stat","path":"/config/peer_pari/peer_pari.conf","expose":false,"statusCode":404,"status":404}
    at /usr/src/app/webpack:/src/modules/wireguard/client.ts:86:11
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:248863:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Error fetching credentials: Internal Server Error {"errno":-2,"code":"ENOENT","syscall":"stat","path":"/config/peer_pari/peer_pari.conf","expose":false,"statusCode":404,"status":404}
    at http://my.dappnode/static/js/main.2b51bdea.chunk.js:1:361526
    at c (http://my.dappnode/static/js/2.23feb42d.chunk.js:2:624195)
    at Generator._invoke (http://my.dappnode/static/js/2.23feb42d.chunk.js:2:623948)
    at Generator.next (http://my.dappnode/static/js/2.23feb42d.chunk.js:2:624554)
    at n (http://my.dappnode/static/js/2.23feb42d.chunk.js:2:2296)
    at s (http://my.dappnode/static/js/2.23feb42d.chunk.js:2:2499)
    at http://my.dappnode/static/js/2.23feb42d.chunk.js:2:2558
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/2.23feb42d.chunk.js:2:2439
    at d (http://my.dappnode/static/js/main.2b51bdea.chunk.js:1:361339)
```

System info:
Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.48
dappmanager.dnp.dappnode.eth: 0.2.43, commit: 4044dae4
https.dnp.dappnode.eth: 0.1.1
ipfs.dnp.dappnode.eth: 0.2.15
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 19.03.8
dockerCliVersion: 19.03.8
os: debian
versionCodename: buster
architecture: amd64

**Comment by vorburger** [comment]
FYI this works for me now, so perhaps this issue could be closed now.

**Comment by ligi** [comment]
For me it still fails with the same error.
